const translateGenreOptions = {
	podcast: {en: [
			{ value: '', label: 'Select Genre' },
			{ value: 'true-crime', label: 'True Crime' },
			{ value: 'comedy', label: 'Comedy' },
			{ value: 'news', label: 'News' },
			{ value: 'business', label: 'Business' },
			{ value: 'technology', label: 'Technology' },
			{ value: 'education', label: 'Education' },
			{ value: 'health', label: 'Health' },
			{ value: 'storytelling', label: 'Storytelling' },
			{ value: 'fiction', label: 'Fiction' },
			{ value: 'sports', label: 'Sports' },
			{ value: 'politics', label: 'Politics' },
			{ value: 'lifestyle', label: 'Lifestyle' },
			{ value: 'science', label: 'Science' },
			{ value: 'history', label: 'History' },
			{ value: 'arts', label: 'Arts' },
		],
		de: [
			{ value: '', label: 'Genre auswählen' },
			{ value: 'true-crime', label: 'Wahre Verbrechen' },
			{ value: 'comedy', label: 'Komödie' },
			{ value: 'news', label: 'Nachrichten' },
			{ value: 'business', label: 'Geschäft' },
			{ value: 'technology', label: 'Technologie' },
			{ value: 'education', label: 'Bildung' },
			{ value: 'health', label: 'Gesundheit' },
			{ value: 'storytelling', label: 'Geschichtenerzählen' },
			{ value: 'fiction', label: 'Fiktion' },
			{ value: 'sports', label: 'Sport' },
			{ value: 'politics', label: 'Politik' },
			{ value: 'lifestyle', label: 'Lebensstil' },
			{ value: 'science', label: 'Wissenschaft' },
			{ value: 'history', label: 'Geschichte' },
			{ value: 'arts', label: 'Kunst' },
		],
		bg: [
			{ value: '', label: 'Изберете жанр' },
			{ value: 'true-crime', label: 'Истински криминални' },
			{ value: 'comedy', label: 'Комедия' },
			{ value: 'news', label: 'Новини' },
			{ value: 'business', label: 'Бизнес' },
			{ value: 'technology', label: 'Технологии' },
			{ value: 'education', label: 'Образование' },
			{ value: 'health', label: 'Здраве' },
			{ value: 'storytelling', label: 'Разкази' },
			{ value: 'fiction', label: 'Художествена литература' },
			{ value: 'sports', label: 'Спорт' },
			{ value: 'politics', label: 'Политика' },
			{ value: 'lifestyle', label: 'Животен стил' },
			{ value: 'science', label: 'Наука' },
			{ value: 'history', label: 'История' },
			{ value: 'arts', label: 'Изкуство' },
		],
	},
	book: {
		bg: [
			{ value: '', label: 'Изберете жанр' },
			{ value: "action", label: "Екшън" },
			{ value: "adventure", label: "Приключенски" },
			{ value: "comedy", label: "Комедия" },
			{ value: "drama", label: "Драма" },
			{ value: "fantasy", label: "Фантастика" },
			{ value: "horror", label: "Ужаси" },
			{ value: "mystery", label: "Мистерия" },
			{ value: "romance", label: "Романтика" },
			{ value: "sci-fi", label: "Научна фантастика" },
			{ value: "thriller", label: "Трилър" }
		],
		de: [
			{ value: '', label: 'Genre auswählen' },
			{ value: "action", label: "Action" },
			{ value: "adventure", label: "Abenteuer" },
			{ value: "comedy", label: "Komödie" },
			{ value: "drama", label: "Drama" },
			{ value: "fantasy", label: "Fantasy" },
			{ value: "horror", label: "Horror" },
			{ value: "mystery", label: "Mystery" },
			{ value: "romance", label: "Romantik" },
			{ value: "sci-fi", label: "Science-Fiction" },
			{ value: "thriller", label: "Thriller" }
		],
		en: [
			{ value: '', label: 'Select Genre' },
			{ value: "action", label: "Action" },
			{ value: "adventure", label: "Adventure" },
			{ value: "comedy", label: "Comedy" },
			{ value: "drama", label: "Drama" },
			{ value: "fantasy", label: "Fantasy" },
			{ value: "horror", label: "Horror" },
			{ value: "mystery", label: "Mystery" },
			{ value: "romance", label: "Romance" },
			{ value: "sci-fi", label: "Science Fiction" },
			{ value: "thriller", label: "Thriller" }
		]
	},
	movie: {
		bg: [
			{ value: '', label: 'Изберете жанр' },
			{ value: "action", label: "Екшън" },
			{ value: "adventure", label: "Приключенски" },
			{ value: "comedy", label: "Комедия" },
			{ value: "drama", label: "Драма" },
			{ value: "fantasy", label: "Фантастика" },
			{ value: "horror", label: "Ужаси" },
			{ value: "mystery", label: "Мистерия" },
			{ value: "romance", label: "Романтика" },
			{ value: "sci-fi", label: "Научна фантастика" },
			{ value: "thriller", label: "Трилър" }
		],
		de: [
			{ value: '', label: 'Genre auswählen' },
			{ value: "action", label: "Action" },
			{ value: "adventure", label: "Abenteuer" },
			{ value: "comedy", label: "Komödie" },
			{ value: "drama", label: "Drama" },
			{ value: "fantasy", label: "Fantasy" },
			{ value: "horror", label: "Horror" },
			{ value: "mystery", label: "Mystery" },
			{ value: "romance", label: "Romantik" },
			{ value: "sci-fi", label: "Science-Fiction" },
			{ value: "thriller", label: "Thriller" }
		],
		en: [
			{ value: '', label: 'Select Genre' },
			{ value: "action", label: "Action" },
			{ value: "adventure", label: "Adventure" },
			{ value: "comedy", label: "Comedy" },
			{ value: "drama", label: "Drama" },
			{ value: "fantasy", label: "Fantasy" },
			{ value: "horror", label: "Horror" },
			{ value: "mystery", label: "Mystery" },
			{ value: "romance", label: "Romance" },
			{ value: "sci-fi", label: "Science Fiction" },
			{ value: "thriller", label: "Thriller" }
		]
	},
	series: {
		bg: [
			{ value: '', label: 'Изберете жанр' },
			{ value: "action", label: "Екшън" },
			{ value: "adventure", label: "Приключенски" },
			{ value: "comedy", label: "Комедия" },
			{ value: "drama", label: "Драма" },
			{ value: "fantasy", label: "Фантастика" },
			{ value: "horror", label: "Ужаси" },
			{ value: "mystery", label: "Мистерия" },
			{ value: "romance", label: "Романтика" },
			{ value: "sci-fi", label: "Научна фантастика" },
			{ value: "thriller", label: "Трилър" }
		],
		de: [
			{ value: '', label: 'Genre auswählen' },
			{ value: "action", label: "Action" },
			{ value: "adventure", label: "Abenteuer" },
			{ value: "comedy", label: "Komödie" },
			{ value: "drama", label: "Drama" },
			{ value: "fantasy", label: "Fantasy" },
			{ value: "horror", label: "Horror" },
			{ value: "mystery", label: "Mystery" },
			{ value: "romance", label: "Romantik" },
			{ value: "sci-fi", label: "Science-Fiction" },
			{ value: "thriller", label: "Thriller" }
		],
		en: [
			{ value: '', label: 'Select Genre' },
			{ value: "action", label: "Action" },
			{ value: "adventure", label: "Adventure" },
			{ value: "comedy", label: "Comedy" },
			{ value: "drama", label: "Drama" },
			{ value: "fantasy", label: "Fantasy" },
			{ value: "horror", label: "Horror" },
			{ value: "mystery", label: "Mystery" },
			{ value: "romance", label: "Romance" },
			{ value: "sci-fi", label: "Science Fiction" },
			{ value: "thriller", label: "Thriller" }
		]
	},


};

export default translateGenreOptions;